FMS/Controllers/FMS_Controller/AdminController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;

namespace FMS.Controllers.FMS_Controller
{
    public class AdminController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /Admin/
        public ActionResult Index()
        {
            return View(db.admin.ToList());
        }

        
        // GET: /Admin/Register
        public ActionResult Register()
        {
            var admin = new Admin();
            return PartialView("Register", admin);
        }

        // POST: /Admin/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "AdminId,AdminUsername,AdminPassword,AdminComfirmPassword")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.admin.Add(admin);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return View();
        }

        //GET: /Admin/Login
        public ActionResult Login()
        {
            return View();
        }

        //POST: /Admin/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Admin user)
        {
            var usr = db.admin.Single(u => u.AdminUsername == user.AdminUsername && u.AdminPassword == user.AdminPassword);
            if (usr != null)
            {
                Session["AdminId"] = usr.AdminId.ToString();
                Session["AdminUsername"] = usr.AdminUsername.ToString();
                return RedirectToAction("LoggedIn");
            }
            else
            {
                ModelState.AddModelError("", "Username or Password is wrong.");
            }
            return View();
        }

        //GET: /Admin/LoggedIn
        public ActionResult LoggedIn()
        {
            if (Session["AdminId"] != null)
            {
                return RedirectToAction("Index", "Restaurant");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }


        // GET: /Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.admin.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", admin);
        }

        // POST: /Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.admin.Find(id);
            db.admin.Remove(admin);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FMS_Controller/StaffController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;
using PagedList;

namespace FMS.Controllers.FMS_Controller
{

    public class StaffController : System.Web.Mvc.Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /Staff/
        [Route("Staff/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            var staffs = db.staff.Where(s => s.RestaurantId == RestaurantId).ToList();
            Session["rName"] = x.RestaurantName;
            Session["rID"] = RestaurantId;

            return View(staffs);
        }

        // GET: /Staff/Create
        public ActionResult Create()
        {
            var staff = new Staff();
            return PartialView("Create", staff);
        }

        // POST: /Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                var s = new Staff
                {
                    RestaurantId = Convert.ToInt32(Session["rID"]),
                    StaffFirstName = staff.StaffFirstName,
                    StaffLastName = staff.StaffLastName,
                    StaffMiddleName = staff.StaffMiddleName,
                    StaffEmail = staff.StaffEmail,
                    StaffAddress = staff.StaffAddress,
                    StaffGender = staff.StaffGender,
                    StaffPhoneNumber = staff.StaffPhoneNumber,
                    StaffDateOfEmployment = staff.StaffDateOfEmployment,
                    StaffDateOfBirth = staff.StaffDateOfBirth,
                    StaffDepartment = staff.StaffDepartment,
                    StaffAccountName = staff.StaffAccountName,
                    StaffAccountNumber = staff.StaffAccountNumber,
                    StaffBank = staff.StaffBank  
                };

                db.staff.Add(s);
                db.SaveChanges();
                return Json(new { success = true});
            }
            return PartialView("Create", staff);
        }

        // GET: /Staff/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantId = new SelectList(db.restaurant, "RestaurantId", "RestaurantName", staff.RestaurantId);
            return PartialView("Edit", staff);
        }

        // POST: /Staff/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            ViewBag.RestaurantId = new SelectList(db.restaurant, "RestaurantId", "RestaurantName", staff.RestaurantId);
            return View("Edit", staff);
        }

        // GET: /Staff/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", staff);
        }

        // POST: /Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.staff.Find(id);
            db.staff.Remove(staff);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Views/Shared/Partial/_MaterialNavbar.cshtml
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">FMS > RESTATURANTS</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="hidden-lg hidden-md">Notifications</p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Mike John responded to your email</a></li>
                        <li><a href="#">You have 5 new tasks</a></li>
                        <li><a href="#">You're now friend with Andrew</a></li>
                        <li><a href="#">Another Notification</a></li>
                        <li><a href="#">Another One</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group  is-empty">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="material-input"></span>
                </div>
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i><div class="ripple-container"></div>
                </button>
            </form>
        </div>
    </div>
</nav>

FMS/Views/Shared/Partial/_MaterialSidebar.cshtml
<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="/img/foood.jpg">
        <!--
            Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

            Tip 2: you can also add an image using data-image tag
        -->
        <div class="logo">
            <a href="#" class="simple-text">
                FMS
            </a>
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="active">
                    <a href="dashboard.html">
                        <i class="material-icons">dashboard</i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Restaurant")">
                        <i class="material-icons">person</i>
                        <p>Restaurant</p>
                    </a>
                </li>
                <li>
                    <a href="table.html">
                        <i class="material-icons">content_paste</i>
                        <p>Food</p>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Staff")">
                        <i class="material-icons">library_books</i>
                        <p>Staff</p>
                    </a>
                </li>
                <li>
                    <a href="icons.html">
                        <i class="material-icons">bubble_chart</i>
                        <p>Users</p>
                    </a>
                </li>
                <li>
                    <a href="maps.html">
                        <i class="material-icons">location_on</i>
                        <p>Income</p>
                    </a>
                </li>
                <li>
                    <a href="notifications.html">
                        <i class="material-icons text-gray">notifications</i>
                        <p>Expense</p>
                    </a>
                </li>
                <li class="active-pro">
                    <a href="@Url.Action("Index", "Admin")">
                        <i class="material-icons">unarchive</i>
                        <p>Admin</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>