FMS/Controllers/FMS_Controller/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FMS.Controllers.FMS_Controller
{
    public class DashboardController : BaseController
    {
        //
        // GET: /Dashboard/
        public ActionResult Index()
        {
            return View();
        }
	}
}

FMS/Controllers/FMS_Controller/IncomeCategoryController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;

namespace FMS.Controllers.FMS_Controller
{
    public class IncomeCategoryController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /IncomeCategory/
        [Route("IncomeCategory/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            Session["ricName"] = x.RestaurantName;
            Session["ricID"] = RestaurantId;

            var incomecategory = db.incomeCategory.Where(ic => ic.RestaurantId == RestaurantId).ToList();
            return View(incomecategory);
        }

        
        // GET: /IncomeCategory/Create
        public ActionResult Create()
        {
            var incomecategory = new IncomeCategory();
            return PartialView("Create", incomecategory);
        }

        // POST: /IncomeCategory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IncomeCategory incomecategory)
        {
            if (ModelState.IsValid)
            {
                var IC = new IncomeCategory
                {
                    RestaurantId = Convert.ToInt32(Session["ricID"]),
                    IncomeCategoryTitle = incomecategory.IncomeCategoryTitle,
                    IncomeCategoryDescription = incomecategory.IncomeCategoryDescription,
                };
                db.incomeCategory.Add(IC);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", incomecategory);
        }

        // GET: /IncomeCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            if (incomecategory == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", incomecategory);
        }

        // POST: /IncomeCategory/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IncomeCategory incomecategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(incomecategory).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", incomecategory);
        }

        // GET: /IncomeCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            if (incomecategory == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", incomecategory);
        }

        // POST: /IncomeCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            db.incomeCategory.Remove(incomecategory);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FMS_Controller/IncomeItemController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;

namespace FMS.Controllers.FMS_Controller
{
    public class IncomeItemController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /IncomeItem/
        [Route ("IncomeItem/Index/{IncomeCategoryId}")]
        public ActionResult Index(int IncomeCategoryId)
        {
            var x = db.incomeCategory.Find(IncomeCategoryId);
            Session["cTitle"] = x.IncomeCategoryTitle;
            Session["cID"] = IncomeCategoryId;

            var incomeitem = db.incomeItem.Where(IT => IT.IncomeCategoryId == IncomeCategoryId).ToList();
            return View(incomeitem);
        }

        // GET: /IncomeItem/Create
        public ActionResult Create()
        {
           
            var incomeitem = new IncomeItem();
            return PartialView("Create", incomeitem);
        }

        // POST: /IncomeItem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IncomeItem incomeitem)
        {
            if (ModelState.IsValid)
            {
                var IC = new IncomeItem
                {
                    IncomeCategoryId = Convert.ToInt32(Session["cID"]),
                    IncomeItemTitle = incomeitem.IncomeItemTitle,
                    IncomeItemPrice = incomeitem.IncomeItemPrice,
                    IncomeItemQuantity = incomeitem.IncomeItemQuantity,
                };
                db.incomeItem.Add(IC);
                db.SaveChanges();
                return Json(new { success = true});
            }

            return PartialView("Create", incomeitem);
        }

        // GET: /IncomeItem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeItem incomeitem = db.incomeItem.Find(id);
            if (incomeitem == null)
            {
                return HttpNotFound();
            }
            
            return PartialView("Edit", incomeitem);
        }

        // POST: /IncomeItem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IncomeItem incomeitem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(incomeitem).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", incomeitem);
        }

        // GET: /IncomeItem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeItem incomeitem = db.incomeItem.Find(id);
            if (incomeitem == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", incomeitem);
        }

        // POST: /IncomeItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IncomeItem incomeitem = db.incomeItem.Find(id);
            db.incomeItem.Remove(incomeitem);
            db.SaveChanges();
            return Json(new { sucess = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FMS_Controller/RestaurantController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;

using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;
namespace FMS.Controllers.FMS_Controller
{
    public class RestaurantController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /Restaurant/
        public ActionResult Index()
        {   
            return View(db.restaurant.ToList());
        }

       
        // GET: /Restaurant/Create
        public ActionResult Create()
        {
            var restaurant = new Restaurant();
            return PartialView("Create", restaurant);
        }

        // POST: /Restaurant/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="RestaurantId,RestaurantName,RestaurantAcronym,RestaurantAddress,LGA,Country,PostalCode")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.restaurant.Add(restaurant);
                db.SaveChanges();
                return Json(new { success = true });
            }


            return PartialView("Create", restaurant);
        }

        // GET: /Restaurant/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Restaurant restaurant = db.restaurant.Find(id);
        //    if (restaurant == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return PartialView("Edit", restaurant);
        //}

        // POST: /Restaurant/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include="RestaurantId, RestaurantName, RestaurantAcronym, RestaurantAddress, LGA, Country, PostalCode")] Restaurant restaurant)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(restaurant).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return Json(new { success = true });
        //    }
        //    return PartialView("Edit", restaurant);
        //}

        // GET: /Restaurant/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete" ,restaurant);
        }

        // POST: /Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.restaurant.Find(id);
            db.restaurant.Remove(restaurant);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Views/IncomeItem/Create.cshtml
@model FMS_Objects.Enities.IncomeItem
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class=" modal-body">
        <div class="container-fluid">
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header" data-background-color="purple">
                                <h3 class="modal-title">Create Income Item</h3>
                            </div>
                            <div class="card-content">
                                <form>
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.IncomeItemId)
                                    @Html.HiddenFor(model => model.IncomeCategoryId)
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemTitle, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemTitle, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemTitle, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemPrice, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemPrice, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemPrice, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemQuantity, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemQuantity, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemQuantity, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <input class="btn btn-primary" type="submit" value="Add" />
                                        <button class="btn btn-warning" data-dismiss="modal">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

FMS/Views/IncomeItem/Delete.cshtml
@model FMS_Objects.Enities.IncomeItem
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

</div>

<div class=" modal-body">
    <div class="container-fluid">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h3 class="modal-title">Deleting @Html.DisplayFor(model => model.IncomeItemTitle)</h3>
                        </div>
                        <div class="card-content">
                            <dl class="dl-horizontal col-md-offset-2">
                                <dt>
                                    @Html.DisplayNameFor(model => model.IncomeCategoryVirtual.IncomeCategoryTitle)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.IncomeCategoryVirtual.IncomeCategoryTitle)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.IncomeItemTitle)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.IncomeItemTitle)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.IncomeItemPrice)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.IncomeItemPrice)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.IncomeItemQuantity)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.IncomeItemQuantity)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="modal-footer">
                                    <input class="btn btn-primary" type="submit" value="Delete" />
                                    <button class="btn btn-warning" data-dismiss="modal">Cancel</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FMS/Views/IncomeItem/Edit.cshtml
@model FMS_Objects.Enities.IncomeItem
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class=" modal-body">
        <div class="container-fluid">
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header" data-background-color="purple">
                                <h3 class="modal-title">Editing @Html.DisplayNameFor(model => model.IncomeItemTitle)</h3>
                            </div>
                            <div class="card-content">
                                <form>
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.IncomeItemId)
                                    @Html.HiddenFor(model => model.IncomeCategoryId)
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemTitle, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemTitle, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemTitle, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemPrice, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemPrice, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemPrice, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.IncomeItemQuantity, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.IncomeItemQuantity, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.IncomeItemQuantity, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <input class="btn btn-primary" type="submit" value="Update" />
                                        <button class="btn btn-warning" data-dismiss="modal">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

FMS/Views/IncomeItem/Index.cshtml
@model IEnumerable<FMS_Objects.Enities.IncomeItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .modal-backdrop {
        z-index: 0;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                <li><a href="@Url.Action("Index", "Restaurant")">Restaurant</a></li>
                <li><a href="@Url.Action("Index", "IncomeCategory", new { id = Convert.ToInt32(Session["cID"]) })"> @Session["cTitle"].ToString() </a></li>
                <li>Income Item</li>   
                <a href="@Url.Action("Create", "IncomeItem")" data-modal="" class="btn btn-primary pull-right">ADD</a>
            </ul>
            
            <div class="card">
                <div class="card-header" data-background-color="purple">
                    <h4 class="title">INCOME ITEMS</h4>
                </div>
                <div class="card-content table-responsive">
                    @using (Html.BeginForm())
                    {
                        <table class="table" id="myTable">
                            <thead class="text-primary">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IncomeItemTitle)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IncomeItemPrice)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IncomeItemQuantity)
                                    </th>
                                    <th>
                                        Actions
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IncomeItemTitle)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IncomeItemPrice)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IncomeItemQuantity)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit", "IncomeItem", new { id = item.IncomeItemId })" data-modal=""><i style="padding-right: 5px" class="fa fa-2x fa-edit"></i></a>
                                            <a href="@Url.Action("Delete", "IncomeItem", new { id = item.IncomeItemId })" data-modal=""><i class="fa fa-2x fa-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>

<script src="~/scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="~/Scripts/Appjs/FMS.js"></script>


<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>