FMS/Controllers/FMS_Controller/FoodController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;
using PagedList;


namespace FMS.Controllers.FMS_Controller
{
    public class FoodController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /Food/
        [Route("Food/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            Session["rNamee"] = x.RestaurantName;
            Session["rID"] = x.RestaurantId;
            
            var food = db.food.Where(f => f.RestaurantId == RestaurantId).ToList();
            return View(food);
        }

        // GET: /Food/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Food food = db.food.Find(id);
        //    if (food == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(food);
        //}

        // GET: /Food/Create
        public ActionResult Create()
        {
            var food = new Food();
            return PartialView("Create", food);
        }

        // POST: /Food/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="FoodId,FoodImage,FoodName,FoodType,FoodPrice,FoodDescription,RestaurantId")] Food food)
        {
            if (ModelState.IsValid)
            {
                var f = new Food
                {
                    RestaurantId = Convert.ToInt32(Session["rID"]),
                    FoodName = food.FoodName,
                    FoodImage = food.FoodImage,
                    FoodDescription = food.FoodDescription,
                    FoodPrice = food.FoodPrice,
                    FoodType = food.FoodType,
                };

                db.food.Add(f);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", food);
        }

        // GET: /Food/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.food.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", food);
        }

        // POST: /Food/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="FoodId,FoodImage,FoodName,FoodType,FoodPrice,FoodDescription,RestaurantId")] Food food)
        {
            if (ModelState.IsValid)
            {
                db.Entry(food).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            ViewBag.RestaurantId = new SelectList(db.restaurant, "RestaurantId", "RestaurantName", food.RestaurantId);
            return View(food);
        }

        // GET: /Food/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.food.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", food);
        }

        // POST: /Food/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Food food = db.food.Find(id);
            db.food.Remove(food);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FMS_Controller/IncomeCategoryController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;

namespace FMS.Controllers.FMS_Controller
{
    public class IncomeCategoryController : Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /IncomeCategory/
        [Route("IncomeCategory/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            Session["ricName"] = x.RestaurantName;
            Session["ricID"] = RestaurantId;

            var incomecategory = db.incomeCategory.Where(ic => ic.RestaurantId == RestaurantId).ToList();
            return View(incomecategory);
        }

        
        // GET: /IncomeCategory/Create
        public ActionResult Create()
        {
            var incomecategory = new IncomeCategory();
            return PartialView("Create", incomecategory);
        }

        // POST: /IncomeCategory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IncomeCategory incomecategory)
        {
            if (ModelState.IsValid)
            {
                var IC = new IncomeCategory
                {
                    RestaurantId = Convert.ToInt32(Session["ricID"]),
                    IncomeCategoryTitle = incomecategory.IncomeCategoryTitle,
                    IncomeCategoryDescription = incomecategory.IncomeCategoryDescription,
                };
                db.incomeCategory.Add(IC);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", incomecategory);
        }

        // GET: /IncomeCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            if (incomecategory == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", incomecategory);
        }

        // POST: /IncomeCategory/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IncomeCategory incomecategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(incomecategory).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", incomecategory);
        }

        // GET: /IncomeCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            if (incomecategory == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", incomecategory);
        }

        // POST: /IncomeCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IncomeCategory incomecategory = db.incomeCategory.Find(id);
            db.incomeCategory.Remove(incomecategory);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FMS_Controller/RestaurantDashboardController.cs
using System.Net;
using System.Web.Mvc;
using System.Data.Entity;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;

namespace FMS.Controllers.FMS_Controller
{
    public class RestaurantDashboardController : Controller
    {
        private StaffDataContext db = new StaffDataContext();
        //
        // GET: /RestaurantDashboard/

        [Route("RestaurantDashboard/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            Session["rName"] = x.RestaurantName;
            Session["rAcronym"] = x.RestaurantAcronym;
            Session["rAddress"] = x.RestaurantAddress;
            Session["rLGA"] = x.LGA;
            Session["rPostalCode"] = x.PostalCode;
            Session["rCountry"] = x.Country;

            Session["rID"] = RestaurantId;
            return View();
        }

        // GET: /Restaurant/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", restaurant);
        }

        // POST: /Restaurant/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RestaurantId, RestaurantName, RestaurantAcronym, RestaurantAddress, LGA, Country, PostalCode")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", restaurant);
        }

        // GET: /Restaurant/Delete/5
        /*public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", restaurant);
        }

        // POST: /Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.restaurant.Find(id);
            db.restaurant.Remove(restaurant);
            db.SaveChanges();
            //return Json(new { success = true });
            return RedirectToAction("Done");
        }*/

        
	}
}

FMS/Controllers/FMS_Controller/StaffController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FMS_DbConnections.DataContext.StaffDataContext;
using FMS_Objects.Enities;
using PagedList;

namespace FMS.Controllers.FMS_Controller
{

    public class StaffController : System.Web.Mvc.Controller
    {
        private StaffDataContext db = new StaffDataContext();

        // GET: /Staff/
        [Route("Staff/Index/{RestaurantId}")]
        public ActionResult Index(int RestaurantId)
        {
            var x = db.restaurant.Find(RestaurantId);
            var staffs = db.staff.Where(s => s.RestaurantId == RestaurantId).ToList();
            Session["rName"] = x.RestaurantName;
            Session["rID"] = RestaurantId;

            return View(staffs);
        }

        // GET: /Staff/Create
        public ActionResult Create()
        {
            var staff = new Staff();
            return PartialView("Create", staff);
        }

        // POST: /Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                var s = new Staff
                {
                    RestaurantId = Convert.ToInt32(Session["rID"]),
                    StaffFirstName = staff.StaffFirstName,
                    StaffLastName = staff.StaffLastName,
                    StaffMiddleName = staff.StaffMiddleName,
                    StaffEmail = staff.StaffEmail,
                    StaffAddress = staff.StaffAddress,
                    StaffGender = staff.StaffGender,
                    StaffPhoneNumber = staff.StaffPhoneNumber,
                    StaffDateOfEmployment = staff.StaffDateOfEmployment,
                    StaffDateOfBirth = staff.StaffDateOfBirth,
                    StaffDepartment = staff.StaffDepartment,
                    StaffAccountName = staff.StaffAccountName,
                    StaffAccountNumber = staff.StaffAccountNumber,
                    StaffBank = staff.StaffBank  
                };

                db.staff.Add(s);
                db.SaveChanges();
                return Json(new { success = true});
            }
            return PartialView("Create", staff);
        }

        // GET: /Staff/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantId = new SelectList(db.restaurant, "RestaurantId", "RestaurantName", staff.RestaurantId);
            return PartialView("Edit", staff);
        }

        // POST: /Staff/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            ViewBag.RestaurantId = new SelectList(db.restaurant, "RestaurantId", "RestaurantName", staff.RestaurantId);
            return View("Edit", staff);
        }

        // GET: /Staff/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", staff);
        }

        // POST: /Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.staff.Find(id);
            db.staff.Remove(staff);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Views/RestaurantDashboard/Delete.cshtml
@model FMS_Objects.Enities.Restaurant
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

</div>

<div class=" modal-body">
    <div class="container-fluid">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h3 class="modal-title">Deleting @Html.DisplayFor(model => model.RestaurantName)</h3>
                        </div>
                        <div class="card-content">
                            
                            <h3 class="text-danger">Are you sure?</h3>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="modal-footer">
                                    <input class="btn btn-danger" type="submit" value="Yes" />
                                    <button class="btn btn-warning" data-dismiss="modal">No</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FMS/Views/RestaurantDashboard/Edit.cshtml
@model FMS_Objects.Enities.Restaurant
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class=" modal-body">
        <div class="container-fluid">
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header" data-background-color="purple">
                                <h3 class="modal-title">Edit @Html.DisplayFor(model => model.RestaurantName)</h3>
                            </div>
                            <div class="card-content">
                                <form>
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.RestaurantId)

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.RestaurantName, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.RestaurantName, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.RestaurantName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.RestaurantAcronym, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.RestaurantAcronym, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.RestaurantAcronym, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.RestaurantAddress, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.RestaurantAddress, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.RestaurantAddress, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.LGA, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.LGA, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.LGA, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.PostalCode, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.PostalCode, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group label-floating">
                                                @Html.LabelFor(model => model.Country, new { @class = "control-label" })
                                                @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <input class="btn btn-primary" type="submit" value="Save" />
                                        <button class="btn btn-warning" data-dismiss="modal">Close</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

FMS/Views/RestaurantDashboard/Index.cshtml
@model IEnumerable<FMS_Objects.Enities.Restaurant>
@using FMS_DbConnections.DAL;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
    FMS_DB db = new FMS_DB();
    int RID = Convert.ToInt32(Session["rID"]);

    var food = db.food.Where(s => s.RestaurantId.Equals(RID)).ToArray().Length;
    var staff = db.staff.Where(s => s.RestaurantId.Equals(RID)).ToArray().Length;
    var income = db.incomeCategory.Where(s => s.RestaurantId.Equals(RID)).ToArray().Length;
    var expense = db.expenseCategory.Where(s => s.RestaurantId.Equals(RID)).ToArray().Length;
    
}

<style>
    .modal-backdrop {
        z-index: 0;
    }

    div#myModal.modal.fade.in{
        overflow: hidden;
    }
</style>

<div class="container-fluid">
 
    <div class="row">
        <div class="col-md-12">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header" data-background-color="purple">
                                <h4 class="title"> @Session["rName"].ToString() </h4>
                            </div>
                            <div class="card-content">
                                <h4><strong>Acronym: </strong>@Session["rAcronym"].ToString() </h4>
                                <h4><strong>Address: </strong>@Session["rAddress"].ToString() </h4>
                                <h4><strong>LGA: </strong>@Session["rLGA"].ToString() </h4>
                                <h4><strong>Postal Code: </strong>@Session["rPostalCode"].ToString() </h4>
                                <h4><strong>Country: </strong>@Session["rCountry"].ToString() </h4>
                                <hr />
                                <a href="@Url.Action("Edit", "RestaurantDashboard", new { id = Convert.ToInt32(Session["rID"]) })" data-modal=""><i style="font-size: small;" class="btn btn-warning fa fa-edit pull-right"> Edit</i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="orange">
                    <i class="material-icons">people</i>
                </div>
                <div class="card-content">
                    <p class="category"><strong>STAFF</strong></p>
                    <h3 class="title"> @staff </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons text-danger">people</i> <a href="@Url.Action("Index","Staff", new { id = Convert.ToInt32(Session["rID"]) })"> View Staffs</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="green">
                    <i class="material-icons">store</i>
                </div>
                <div class="card-content">
                    <p class="category"><strong>FOOD</strong></p>
                    <h3 class="title"> @food </h3>
                </div> 
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">date_range</i><a href="@Url.Action("Index","Food", new { id = Convert.ToInt32(Session["rID"]) })"> View Food</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="red">
                    <i class="material-icons">info_outline</i>
                </div>
                <div class="card-content">
                    <p class="category"><strong>INCOME</strong></p>
                    <h3 class="title"> @income</h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">local_offer</i><a href="@Url.Action("Index","IncomeCategory", new { id = Convert.ToInt32(Session["rID"]) })"> View Income</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="blue">
                    <i class="fa fa-money"></i>
                </div>
                <div class="card-content">
                    <p class="category"><strong>EXPENSE</strong></p>
                    <h3 class="title">+@expense</h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">update</i><a href="@Url.Action("Index","ExpenseCategory", new { id = Convert.ToInt32(Session["rID"]) })">View Expense</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="blue">
                    <i class="fa fa-money"></i>
                </div>
                <div class="card-content">
                    <p class="category"><strong>SALARY</strong></p>
                    <h3 class="title">+245</h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">update</i><a href="@Url.Action("Index","ExpenseCategory", new { id = Convert.ToInt32(Session["rID"]) })">View Expense</a>
                    </div>
                </div>
            </div>
        </div>
        <!--div-- class="row">
            
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header card-chart" data-background-color="green">
                            <div class="ct-chart" id="dailySalesChart"></div>
                        </div>
                        <div class="card-content">
                            <h4 class="title">Daily Sales</h4>
                            <p class="category"><span class="text-success"><i class="fa fa-long-arrow-up"></i> 55%  </span> increase in today sales.</p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <i class="material-icons">access_time</i> updated 4 minutes ago
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header card-chart" data-background-color="orange">
                            <div class="ct-chart" id="emailsSubscriptionChart"></div>
                        </div>
                        <div class="card-content">
                            <h4 class="title">Email Subscriptions</h4>
                            <p class="category">Last Campaign Performance</p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <i class="material-icons">access_time</i> campaign sent 2 days ago
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header card-chart" data-background-color="red">
                            <div class="ct-chart" id="completedTasksChart"></div>
                        </div>
                        <div class="card-content">
                            <h4 class="title">Completed Tasks</h4>
                            <p class="category">Last Campaign Performance</p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <i class="material-icons">access_time</i> campaign sent 2 days ago
                            </div>
                        </div>
                    </div>
                </div>
            </div-->
        </div>
    </div>

<!--Modal Placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Appjs/FMS.js"></script>